/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    1: typeof import('./src/components/1.vue')['default']
    BidsTenders: typeof import('./src/components/BidsTenders.vue')['default']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    EditInstance: typeof import('./src/components/EditInstance.vue')['default']
    EditInventory: typeof import('./src/components/EditInventory.vue')['default']
    EditInventoryDR: typeof import('./src/components/EditInventoryDR.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    InfraInventory: typeof import('./src/components/InfraInventory.vue')['default']
    InfraInventoryDR: typeof import('./src/components/InfraInventoryDR.vue')['default']
    Instancegrid: typeof import('./src/components/InstanceGrid.vue')['default']
    InstanceGrid: typeof import('./src/components/InstanceGrid.vue')['default']
    InstanceSection: typeof import('./src/components/InstanceSection.vue')['default']
    InstanceSetting: typeof import('./src/components/InstanceSetting.vue')['default']
    InventoryGrid: typeof import('./src/components/InventoryGrid.vue')['default']
    InventoryGridDR: typeof import('./src/components/InventoryGridDR.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PortalSettings: typeof import('./src/components/PortalSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Storageform: typeof import('./src/components/Storageform.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    TopSection: typeof import('./src/components/TopSection.vue')['default']
  }
}
